export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as Sidebar} from './Sidebar'
export {default as Slider} from './Slider'
export {default as Hero} from './Hero'
export {default as Team} from './Team'
export {default as SubjectItem} from './SubjectItem'